# Dockerfile.dev

# Utiliser l'image Node.js appropriée
FROM node:20-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances de développement
RUN npm install

# Copier le reste du code source
COPY . .

# Exposer le port de l'application
EXPOSE 8000

# Commande de démarrage en mode développement
CMD ["npm", "run", "dev"]