services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: database
      SERVER_PORT: 8000 
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: node dist/index.js

  app_test:
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: database
    depends_on:
      - db
    command: npm test

volumes:
  db_data:
