name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Déploie automatiquement les commits sur main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: dentarg/heroku@v1
        with:
          app: "back-projet-web-s7" 
          key: ${{ secrets.HEROKU_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}